/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 console.gltf --transform 
Files: console.gltf [1.46MB] > C:\Users\Jake\Desktop\gameboymodel\console-transformed.glb [59.36KB] (96%)
Author: LisHard (https://sketchfab.com/lishard4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-boy-challenge-a91c7818d2aa4331aabb3962b29548be
Title: Game Boy Challenge
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function Model(props) {
//   const { nodes, materials } = useGLTF('/console-transformed.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.GameBoy_GameBoy_Mat_0.geometry} material={materials.GameBoy_Mat} rotation={[-0.208, 0.009, 0.338]} scale={0.006} />
//     </group>
//   )
// }

// useGLTF.preload('/console-transformed.glb')

//TO REMOVE BEFORE HOSTING